definitions:
  dto.BaseJSONResp:
    properties:
      code:
        type: integer
      data: {}
      detail: {}
      message:
        type: string
    type: object
  dto.CreateBookReq:
    properties:
      category_uuid:
        type: string
      stock:
        type: integer
      title:
        type: string
    required:
    - stock
    - title
    type: object
  dto.CreateBookResp:
    properties:
      author_uuid:
        type: string
      category_uuid:
        type: string
      created_at:
        type: string
      stock:
        type: integer
      title:
        type: string
      updated_at:
        type: string
      uuid:
        type: string
    type: object
info:
  contact: {}
  title: Book Service RESTful API
paths:
  /books:
    post:
      parameters:
      - description: payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/dto.CreateBookReq'
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/dto.BaseJSONResp'
            - properties:
                data:
                  $ref: '#/definitions/dto.CreateBookResp'
              type: object
      security:
      - BearerAuth: []
      summary: Create new author
      tags:
      - Books
securityDefinitions:
  BearerAuth:
    description: JWT Authorization header using the Bearer scheme (add 'Bearer ' prefix).
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
