version: '3.8'

services:
  backend_syn_db:
    image: postgres:13
    container_name: backend_syn_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network
    env_file:
      - .env

volumes:
  postgres_data:

networks:
  my_network:
    driver: bridge