// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.0
// source: book.proto

package book

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthService_GetBookTotalByAuthorUUID_FullMethodName      = "/book_service.AuthService/GetBookTotalByAuthorUUID"
	AuthService_BulkGetBookTotalByAuthorUUIDs_FullMethodName = "/book_service.AuthService/BulkGetBookTotalByAuthorUUIDs"
)

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthServiceClient interface {
	GetBookTotalByAuthorUUID(ctx context.Context, in *GetBookTotalByAuthorUUIDReq, opts ...grpc.CallOption) (*GetBookTotalByAuthorUUIDResp, error)
	BulkGetBookTotalByAuthorUUIDs(ctx context.Context, in *BulkGetBookTotalByAuthorUUIDsReq, opts ...grpc.CallOption) (*BulkGetBookTotalByAuthorUUIDsResp, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) GetBookTotalByAuthorUUID(ctx context.Context, in *GetBookTotalByAuthorUUIDReq, opts ...grpc.CallOption) (*GetBookTotalByAuthorUUIDResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBookTotalByAuthorUUIDResp)
	err := c.cc.Invoke(ctx, AuthService_GetBookTotalByAuthorUUID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) BulkGetBookTotalByAuthorUUIDs(ctx context.Context, in *BulkGetBookTotalByAuthorUUIDsReq, opts ...grpc.CallOption) (*BulkGetBookTotalByAuthorUUIDsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BulkGetBookTotalByAuthorUUIDsResp)
	err := c.cc.Invoke(ctx, AuthService_BulkGetBookTotalByAuthorUUIDs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
// All implementations must embed UnimplementedAuthServiceServer
// for forward compatibility.
type AuthServiceServer interface {
	GetBookTotalByAuthorUUID(context.Context, *GetBookTotalByAuthorUUIDReq) (*GetBookTotalByAuthorUUIDResp, error)
	BulkGetBookTotalByAuthorUUIDs(context.Context, *BulkGetBookTotalByAuthorUUIDsReq) (*BulkGetBookTotalByAuthorUUIDsResp, error)
	mustEmbedUnimplementedAuthServiceServer()
}

// UnimplementedAuthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthServiceServer struct{}

func (UnimplementedAuthServiceServer) GetBookTotalByAuthorUUID(context.Context, *GetBookTotalByAuthorUUIDReq) (*GetBookTotalByAuthorUUIDResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBookTotalByAuthorUUID not implemented")
}
func (UnimplementedAuthServiceServer) BulkGetBookTotalByAuthorUUIDs(context.Context, *BulkGetBookTotalByAuthorUUIDsReq) (*BulkGetBookTotalByAuthorUUIDsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BulkGetBookTotalByAuthorUUIDs not implemented")
}
func (UnimplementedAuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {}
func (UnimplementedAuthServiceServer) testEmbeddedByValue()                     {}

// UnsafeAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServiceServer will
// result in compilation errors.
type UnsafeAuthServiceServer interface {
	mustEmbedUnimplementedAuthServiceServer()
}

func RegisterAuthServiceServer(s grpc.ServiceRegistrar, srv AuthServiceServer) {
	// If the following call pancis, it indicates UnimplementedAuthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthService_ServiceDesc, srv)
}

func _AuthService_GetBookTotalByAuthorUUID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBookTotalByAuthorUUIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetBookTotalByAuthorUUID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_GetBookTotalByAuthorUUID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetBookTotalByAuthorUUID(ctx, req.(*GetBookTotalByAuthorUUIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_BulkGetBookTotalByAuthorUUIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BulkGetBookTotalByAuthorUUIDsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).BulkGetBookTotalByAuthorUUIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_BulkGetBookTotalByAuthorUUIDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).BulkGetBookTotalByAuthorUUIDs(ctx, req.(*BulkGetBookTotalByAuthorUUIDsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthService_ServiceDesc is the grpc.ServiceDesc for AuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "book_service.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBookTotalByAuthorUUID",
			Handler:    _AuthService_GetBookTotalByAuthorUUID_Handler,
		},
		{
			MethodName: "BulkGetBookTotalByAuthorUUIDs",
			Handler:    _AuthService_BulkGetBookTotalByAuthorUUIDs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "book.proto",
}
